FROM python:3.14-rc-alpine

RUN apk add --no-cache build-base libffi-dev python3-dev

RUN pip3 install -U aliyun-log-cli --no-cache

RUN wget https://aliyuncli.alicdn.com/aliyun-cli-linux-latest-amd64.tgz \
    && tar -xvzf aliyun-cli-linux-latest-amd64.tgz \
    && rm aliyun-cli-linux-latest-amd64.tgz \
    && mv aliyun /usr/local/bin/

WORKDIR /app
